<a href="https://colab.research.google.com/github/anujsanap25-nxtwave/Data_science_lab_SE_72/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
print("Create a 3x3 square matrix and compute its determinant.")

Create a 3x3 square matrix and compute its determinant.


In [9]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [4,8,9]])

print("The 3*3 matrix is: ")
print(matrix)

determinant = np.linalg.det(matrix)

print(f"\nThe determinant of the matrix is: {determinant}")


The 3*3 matrix is: 
[[1 2 3]
 [4 5 6]
 [4 8 9]]

The determinant of the matrix is: 9.000000000000002


In [10]:
print("Find the inverse of the matrix.")

Find the inverse of the matrix.


In [11]:
import numpy as np
matrix = np.array([
    [1,2,3],
    [0,1,4],
    [5,6,0]
])

print("Original 3*3 matrix: ")
print(matrix)

try:
  inverse_matrix = np.linalg.inv(matrix)
  print("\nInverse of the matrix:")
  print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nError: The matrix is singular and does not have an inverse.")

Original 3*3 matrix: 
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [12]:
print("Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20")

Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20


In [13]:
import numpy as np
A = np.array([[2,3],
              [4,5]])
B = np.array([10,20])

x,y = np.linalg.solve(A,B)
print(f"the solution is: x = {x:.2f}, y = {y:.2f}")

the solution is: x = 5.00, y = 0.00
